Fix some imports
Still get:
ERROR in ./app/app.css
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: Failed to find '~@nativescript/theme/core'
  in [
    /Users/edjones/apps/nativescript-ui-samples-vue/listview/app
  ]
    at /Users/edjones/apps/nativescript-ui-samples-vue/listview/node_modules/postcss-import/lib/resolve-id.js:35:13
    at async Promise.all (index 0)
    at async LazyResult.runAsync (/Users/edjones/apps/nativescript-ui-samples-vue/listview/node_modules/postcss/lib/lazy-result.js:396:11)
    at async Object.loader (/Users/edjones/apps/nativescript-ui-samples-vue/listview/node_modules/postcss-loader/dist/index.js:95:14)
 @ ./app/main.ts 2:0-19

webpack 5.74.0 compiled with 1 error in 72 ms
Webpack compilation complete. Watching for file changes.
ERROR in ./app/main.ts:9:5
TS2339: Property 'use' does not exist on type 'NativeScriptVueConstructor<View>'.
     7 | import RadListView from 'nativescript-ui-listview/vue';
     8 |
  >  9 | Vue.use(RadListView);
       |     ^^^
    10 | // << listview-vue-import
    11 | for (let comp of getExamples()) {
    12 |   Vue.component(comp.name, comp);

ERROR in ./app/main.ts:12:7
TS2339: Property 'component' does not exist on type 'NativeScriptVueConstructor<View>'.
    10 | // << listview-vue-import
    11 | for (let comp of getExamples()) {
  > 12 |   Vue.component(comp.name, comp);
       |       ^^^^^^^^^
    13 | }
    14 |
    15 | Vue.component(views.Home.name, views.Home);

ERROR in ./app/main.ts:15:5
TS2339: Property 'component' does not exist on type 'NativeScriptVueConstructor<View>'.
    13 | }
    14 |
  > 15 | Vue.component(views.Home.name, views.Home);
       |     ^^^^^^^^^
    16 |
    17 | // Vue.config.silent = false;
    18 |

ERROR in ./app/main.ts:19:5
TS2351: This expression is not constructable.
  Type 'NativeScriptVueConstructor<View>' has no construct signatures.
    17 | // Vue.config.silent = false;
    18 |
  > 19 | new Vue({
       |     ^^^
    20 |   template: `
    21 |     <Frame>
    22 |       <Home />

Found 4 errors in 93 ms.